name: Cypress Tests

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: cypress-tests
        if: failure()